[#387] bump keyclaok
hzi-braunschweig/SORMAS-Docker pull request #388
Opened 2022-06-21 13:34 UTC by JonasCir

fixes 387

2022-07-18 10:21 UTC, JonasCir commented
Build wont work currently as I decided to changed the import, but still good to review to get a first impression...

2022-07-18 11:45 UTC, JonasCir commented
Unfortunately blocked on https://github.com/keycloak/keycloak/issues/12939 it seems

2022-07-18 12:25 UTC, JonasCir commented
Also filed https://github.com/keycloak/keycloak/issues/13171, but not certain if this is important

2022-09-23 09:09 UTC, fhauptmann commented
Keycloak 18 has been cancelled until blocking tasks have been resolved

2023-03-07 09:21 UTC, MartinWahnschaffe commented
I have fixed the config import problem and updated keycloak to 21.0.1. All changes have also been reflected in the description above.

2023-03-08 07:38 UTC, MartinWahnschaffe requested changes

2023-03-08 07:38 UTC, MartinWahnschaffe commented on .env
>  KEYCLOAK_DB_NAME=keycloak
Remove this, as it's no longer used

2023-03-08 07:38 UTC, MartinWahnschaffe commented on keycloak/update-realm.sh
> -${KCADM} create partialImport -r SORMAS -s ifResourceExists=SKIP -o -f ./SORMAS.json
The functionality to add new resources to the realm by importing the SORMAS.json after startup is missing now. The `kc start --import-realm` command will skip the realm completely if it already exists.

2023-03-08 07:38 UTC, MartinWahnschaffe commented on services-base.yml
> +      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8080/auth/" ]
Does not work since curl is no longer available. Also /auth is the wrong path.

2023-03-08 10:44 UTC, MartinWahnschaffe approved these changes

2023-03-10 12:48 UTC, fhauptmann commented
Successfully deployed

2023-03-10 13:02 UTC, tnako-sg approved these changes

2023-03-10 13:02 UTC, merged

2023-03-10 13:02 UTC, fhauptmann approved these changes